#docker-compose.yaml
version: "3.9"

volumes:
  vol-mbanking:

services:
  sbc11-postgres:
    image: "postgres:16.4-bullseye"
    container_name: "mbanking-postgres"
    ports:
      - "6666:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin
      POSTGRES_USER: postgres
      POSTGRES_DB: db_mbanking
    volumes:
      - "vol-mbanking:/var/lib/postgresql/data"
